### ISSUE TITLE
learn basics TypeScript

### ISSUE THREAD

**Issue by pharvisfargo** [bregySilvan/TabSolution#2]
#### Description
learn needed languages for the coming projects 

-  refresh JS know-how
-  learn the basics of typescript
-  Angular?

**Comment by Christian-Seematter** [comment]
For those who have never worked with TypeScript, you can use [TypeScript in 5 minutes](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) to get started

The only thing you need to do first is install node: https://nodejs.org/en/

**Comment by bregySilvan** [comment]
## Note

I started to create something like a little Typescript Wiki. I will update it during the module. It was created at hazu.io since i'll maybe need it in the future again. 
Everyone is allowed to help me creating it, just ask me and i will grant u access.


https://hazu.io/silvan/code/typescript

**Comment by Christian-Seematter** [comment]
@bregySilvan Just send out invitations to the email addresses you added to this repo.

**Comment by Christian-Seematter** [comment]
Had the lecture today about TypeScript basics, all documents are on gdrive.

The branch "TypeScript-Demos" contains examples to play with.
